routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    if (config('auth.users.registration')) {
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

    // Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    Route::get('permissions', 'PermissionController@index')->name('permissions');
    Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
    Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
    Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');

    // Categories
    Route::get('categories', 'CategoryController@index')->name('categories.index');
    Route::get('categories/create', 'CategoryController@create')->name('categories.create');
    Route::get('categories/{category}/edit', 'CategoryController@edit')->name('categories.edit');
    Route::get('categories/getTableData', 'CategoryController@getTableData');
    Route::post('categories/store', 'CategoryController@store')->name('categories.store');
    Route::put('categories/{category}', 'CategoryController@update')->name('categories.update');
    Route::delete('categories/destroy/{category}', 'CategoryController@destroy');

    // Units
    Route::get('unit', 'UnitController@index')->name('unit.index');
    Route::get('unit/create', 'UnitController@create')->name('unit.create');
    Route::get('unit/{category}/edit', 'UnitController@edit')->name('unit.edit');
    Route::get('unit/getTableData', 'UnitController@getTableData');
    Route::post('unit/store', 'UnitController@store')->name('unit.store');
    Route::put('unit/{category}', 'UnitController@update')->name('unit.update');
    Route::delete('unit/destroy/{category}', 'UnitController@destroy');
});

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::resource('/shopping_list', 'ShoppingListResource');

/**
 * Membership
 */
Route::group(['as' => 'protection.'], function () {
    Route::get('membership', 'MembershipController@index')->name('membership')->middleware('protection:' . config('protection.membership.product_module_number') . ',protection.membership.failed');
    Route::get('membership/access-denied', 'MembershipController@failed')->name('membership.failed');
    Route::get('membership/clear-cache/', 'MembershipController@clearValidationCache')->name('membership.clear_validation_cache');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreCategory;
use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Support\Facades\Lang;
use App\Http\Requests\UpdateCategory;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreCategory $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(StoreCategory $request)
    {
        $category = new Category();
        $category->name = $request->get('name');

        $result = $category->save();

        if ( ! $result) {
            $this->response['error'] = true;
            $this->response['message'] = Lang::get('category.add_error');
            return response()->json($this->response);
        }

        $this->response['message'] = Lang::get('category.add_success');
        return response()->json($this->response);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.category.edit', ['category' => Category::find($id)->first()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateCategory $request
     * @param Category $category
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(UpdateCategory $request, Category $category)
    {
        $category->name = $request->get('name');

        $result = $category->save();

        if ( ! $result) {
            $this->response['error'] = true;
            $this->response['message'] = Lang::get('category.update_error');
            return response()->json($this->response);
        }

        $this->response['message'] = Lang::get('category.update_success');
        return response()->json($this->response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = Category::destroy('id', $id);

        if ( ! $result) {
            $this->response['error'] = true;
            $this->response['message'] = Lang::get('category.destroy_error');
            return response()->json($this->response);
        }

        $this->response['message'] = Lang::get('category.destroy_success');
        return response()->json($this->response);
    }

    /**
     * Response data for dataTable
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getTableData ()
    {
        return response()->json([
            'data' => Category::all()
        ]);
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.layouts.admin')

@section('title',  __('views.admin.category.create.title'))

@section('content')

    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ __('views.admin.category.create.header_1') }}</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <form id="category-form" action="{{ route('admin.categories.store') }}" method="POST" class="form-horizontal ">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                {{ __('views.admin.category.create.label_1') }}
                                <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input type="text" name="name" id="name" class="form-control" placeholder="{{ __('views.admin.category.create.placeholder_1') }}">
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                                <button class="btn btn-primary" type="reset">{{ __('views.admin.category.create.btn_title_1') }}</button>
                                <button type="submit" class="btn btn-success">{{ __('views.admin.category.create.btn_title_2') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/category/create.js')) }}
@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layouts.admin')

@section('title', __('views.admin.category.edit.title'))

@section('content')

    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ __('views.admin.category.edit.header_1') }}</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <form id="edit-form" action="{{ route('admin.categories.update', $category->id ) }}" method="PUT" class="form-horizontal">
                        <input type="hidden" name="id" value="{{ $category->id }}">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                {{ __('views.admin.category.edit.label_1') }}
                                <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input type="text"
                                       name="name"
                                       id="name"
                                       class="form-control"
                                       value="{{ $category->name }}"
                                       placeholder="{{ __('views.admin.category.edit.placeholder_1') }}">
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                                <button class="btn btn-primary" type="reset">{{ __('views.admin.category.edit.btn_title_1') }}</button>
                                <button type="submit" class="btn btn-success">{{ __('views.admin.category.edit.btn_title_2') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/category/edit.js')) }}
@endsection

resources/views/admin/category/index.blade.php
@extends('admin.layouts.admin')

@section('title', __('views.admin.category.index.title'))

@section('content')

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ __('views.admin.category.index.header_1') }}</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="categories-table"
                           class="table table-striped table-bordered dt-responsive nowrap"
                           cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>{{ __('views.admin.category.index.table_header_1') }}</th>
                                <th>{{ __('views.admin.category.index.table_header_2') }}</th>
                                <th>{{ __('views.admin.category.index.table_header_3') }}</th>
                                <th>{{ __('views.admin.category.index.table_header_4') }}</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>{{ __('views.admin.category.index.table_header_1') }}</th>
                                <th>{{ __('views.admin.category.index.table_header_2') }}</th>
                                <th>{{ __('views.admin.category.index.table_header_3') }}</th>
                                <th>{{ __('views.admin.category.index.table_header_4') }}</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {{-- Шаблон предупреждения об удалении категории --}}
    <script id="destroy-category" type="text/template">
        <p>{{ __('views.admin.category.index.warning_1') }} "@{{ name }}"?</p>
    </script>


    {{-- Шаблон кнопок в колонках таблицы --}}
    <script id="actionButtonsTemplate" type="text/template">
        <a class="btn btn-xs btn-info"
           target="_blank"
           href="/admin/categories/@{{ id }}/edit"
           data-toggle="tooltip"
           data-placement="top"
           title="{{ __('views.admin.category.index.btn_title_1') }}  | {{ __('views.admin.category.index.btn_title_2') }}">
            <i class="fa fa-pencil"></i>
        </a>

        <button class="btn btn-xs btn-danger btn-category-destroy"
                data-toggle="tooltip"
                data-placement="top"
                title="{{ __('views.admin.category.index.btn_title_3') }}"
                data-id="@{{ id }}"
                data-category-name="@{{ name }}">
            <i class="fa fa-trash"></i>
        </button>
    </script>

@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/category/index.js')) }}
@endsection