routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    if (config('auth.users.registration')) {
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

    // Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    Route::get('permissions', 'PermissionController@index')->name('permissions');
    Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
    Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
    Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');

    // Categories
    Route::get('categories', 'CategoryController@index')->name('categories.index');
    Route::get('categories/create', 'CategoryController@create')->name('categories.create');
    Route::get('categories/{category}/edit', 'CategoryController@edit')->name('categories.edit');
    Route::get('categories/getTableData', 'CategoryController@getTableData');
    Route::post('categories/store', 'CategoryController@store')->name('categories.store');
    Route::put('categories/{category}', 'CategoryController@update')->name('categories.update');
    Route::delete('categories/destroy/{category}', 'CategoryController@destroy');

    // Units
    Route::get('unit', 'UnitController@index')->name('unit.index');
    Route::get('unit/create', 'UnitController@create')->name('unit.create');
    Route::get('unit/{category}/edit', 'UnitController@edit')->name('unit.edit');
    Route::get('unit/getTableData', 'UnitController@getTableData');
    Route::post('unit/store', 'UnitController@store')->name('unit.store');
    Route::put('unit/{category}', 'UnitController@update')->name('unit.update');
    Route::delete('unit/destroy/{category}', 'UnitController@destroy');
});

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::resource('/shopping_list', 'ShoppingListResource');

/**
 * Membership
 */
Route::group(['as' => 'protection.'], function () {
    Route::get('membership', 'MembershipController@index')->name('membership')->middleware('protection:' . config('protection.membership.product_module_number') . ',protection.membership.failed');
    Route::get('membership/access-denied', 'MembershipController@failed')->name('membership.failed');
    Route::get('membership/clear-cache/', 'MembershipController@clearValidationCache')->name('membership.clear_validation_cache');
});

app/Models/Unit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    //
}

app/Http/Controllers/Admin/UnitController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreUnit;
use App\Http\Requests\UpdateUnit;
use App\Models\Unit;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Lang;

class UnitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.unit.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.unit.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreUnit $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(StoreUnit $request)
    {
        $unit = new Unit();
        $unit->name = $request->get('name');

        $result = $unit->save();

        if ( ! $result) {
            $this->response['error'] = true;
            $this->response['message'] = Lang::get('unit.add_error');
            return response()->json($this->response);
        }

        $this->response['message'] = Lang::get('unit.success');
        return response()->json($this->response);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.unit.edit', ['unit' => Unit::find($id)->first()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateUnit $request
     * @param Unit $unit
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(UpdateUnit $request, Unit $unit)
    {
        $unit->name = $request->get('name');

        $result = $unit->save();

        if ( ! $result) {
            $this->response['error'] = true;
            $this->response['message'] = Lang::get('unit.update_error');
            return response()->json($this->response);
        }

        $this->response['message'] = Lang::get('unit.update_success');
        return response()->json($this->response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = Unit::destroy('id', $id);

        if ( ! $result) {
            $this->response['error'] = true;
            $this->response['message'] = Lang::get('unit.destroy_error');
            return response()->json($this->response);
        }

        $this->response['message'] = Lang::get('unit.destroy_success');
        return response()->json($this->response);
    }

    /**
     * Response data for dataTable
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getTableData ()
    {
        return response()->json([
            'data' => Unit::all()
        ]);
    }
}

resources/views/admin/unit/create.blade.php
@extends('admin.layouts.admin')

@section('title', __('views.admin.unit.create.title'))

@section('content')

    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ __('views.admin.unit.create.header_1') }}</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form id="unit-form" action="{{ route('admin.unit.store') }}" method="POST" class="form-horizontal ">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                {{ __('views.admin.unit.create.label_1') }}
                                <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input type="text" name="name" id="name" class="form-control" placeholder="{{ __('views.admin.unit.create.placeholder_1') }}">
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                                <button class="btn btn-primary" type="reset">{{ __('views.admin.unit.create.btn_title_1') }}</button>
                                <button type="submit" class="btn btn-success">{{ __('views.admin.unit.create.btn_title_2') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/unit/create.js')) }}
@endsection

resources/views/admin/unit/edit.blade.php
@extends('admin.layouts.admin')

@section('title', __('views.admin.unit.edit.title'))

@section('content')

    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ __('views.admin.unit.edit.header_1') }}</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <form id="edit-form" action="{{ route('admin.unit.update', $unit->id ) }}" method="PUT" class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                {{ __('views.admin.unit.edit.label_1') }}
                                <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input type="text"
                                       name="name"
                                       id="name"
                                       class="form-control"
                                       value="{{ $unit->name }}"
                                       placeholder="{{ __('views.admin.unit.edit.placeholder_1') }}">
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                                <button class="btn btn-primary" type="reset">{{ __('views.admin.unit.edit.btn_title_1') }}</button>
                                <button type="submit" class="btn btn-success">{{ __('views.admin.unit.edit.btn_title_2') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/category/edit.js')) }}
@endsection

resources/views/admin/unit/index.blade.php
@extends('admin.layouts.admin')

@section('title', __('views.admin.unit.index.title'))

@section('content')

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ __('views.admin.unit.index.header_1') }}</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="unit-table"
                           class="table table-striped table-bordered dt-responsive nowrap"
                           cellspacing="0"
                           width="100%">
                        <thead>
                            <tr>
                                <th>{{ __('views.admin.unit.index.table_header_1') }}</th>
                                <th>{{ __('views.admin.unit.index.table_header_2') }}</th>
                                <th>{{ __('views.admin.unit.index.table_header_3') }}</th>
                                <th>{{ __('views.admin.unit.index.table_header_4') }}</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>{{ __('views.admin.unit.index.table_header_1') }}</th>
                                <th>{{ __('views.admin.unit.index.table_header_2') }}</th>
                                <th>{{ __('views.admin.unit.index.table_header_3') }}</th>
                                <th>{{ __('views.admin.unit.index.table_header_4') }}</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {{-- Шаблон предупреждения об удалении ед. измер. --}}
    <script id="destroy-unit" type="text/template">
        <p>{{ __('views.admin.unit.index.warning_1') }} -  "@{{ name }}"?</p>
    </script>


    {{-- Шаблон кнопок в колонках таблицы --}}
    <script id="actionButtonsTemplate" type="text/template">
        <a class="btn btn-xs btn-info"
           target="_blank"
           href="/admin/unit/@{{ id }}/edit"
           data-toggle="tooltip"
           data-placement="top"
           title="{{ __('views.admin.unit.index.btn_title_1') }}  |  {{ __('views.admin.unit.index.btn_title_2') }}">
            <i class="fa fa-pencil"></i>
        </a>

        <button class="btn btn-xs btn-danger btn-unit-destroy"
                data-toggle="tooltip"
                data-placement="top"
                title="{{ __('views.admin.unit.index.btn_title_3') }}"
                data-id="@{{ id }}"
                data-unit-name="@{{ name }}">
            <i class="fa fa-trash"></i>
        </button>
    </script>

@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/unit/index.js')) }}
@endsection